# -*- coding: utf-8 -*-
"""Mouse Moving Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJYYLbc0_lgHW_E0tEmewxuNzZ3rVSzg
"""

!pip install pyautogui

import pyautogui as pag
import random
import time

while True:
  x=random.randiant(500,700)
  y=random.randiant(200,600)
  time.sleep(2)